---
version: '3'
services:
  jirafeau:
    build: https://gitlab.com/mojo42/Jirafeau.git
    image: jirafeau:arm32v7-latest
    container_name: jirafeau
    environment:
      - title='My Title'
    ports:
      - 3004:80
    restart: unless-stopped