---
version: '3.3'
volumes:
  data:
services:
  jirafeau:
    build: https://gitlab.com/mojo42/Jirafeau.git
    image: jirafeau:arm32v7-latest
    container_name: jirafeau
    environment:
      - PUID=82
      - PGID=82
    volumes:
      - type: bind
        source: ${PWD}/config.local.php
        target: /www/lib/config.local.php
      - type : volume
        source: data
        target: /var/lib/jirafeau/data
    ports:
      - 3004:80
    restart: unless-stopped