---
version: '3'
volumes:
  data:
services:
  jirafeau:
    build: https://gitlab.com/mojo42/Jirafeau.git
    image: jirafeau:arm32v7-latest
    container_name: jirafeau
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
#      - ./config.local.php:/www/lib/config.local.php
      - data:/var/lib/jirafeau/data
    ports:
      - 3004:80
    restart: unless-stopped